apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: kammana/nodeapp:v1
      ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: apps1 
   namespace: ns-dev
spec: 
  matchlabels:
  